version: "3"
services:
  app:
    container_name: apollonia-app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/apollonia
  db:
    container_name: apollonia-db
    image: mongo:latest
    ports:
      - "27017:27017"
